name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        run: pnpm env use -g 22
        timeout-minutes: 1

      - name: Install dependencies
        run: pnpm install
        timeout-minutes: 1

      - name: Run lint
        run: |
          pnpm cspell --no-summary --no-progress .
          pnpm biome ci .
        timeout-minutes: 1

      - name: Run tests
        # TODO: run only related tests
        run: pnpm test
        timeout-minutes: 1
